// Generated by gencpp from file utils/cmd_vel.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_CMD_VEL_H
#define UTILS_MESSAGE_CMD_VEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct cmd_vel_
{
  typedef cmd_vel_<ContainerAllocator> Type;

  cmd_vel_()
    : v_left(0.0)
    , v_right(0.0)
    , v_left_stm(0.0)
    , v_right_stm(0.0)  {
    }
  cmd_vel_(const ContainerAllocator& _alloc)
    : v_left(0.0)
    , v_right(0.0)
    , v_left_stm(0.0)
    , v_right_stm(0.0)  {
  (void)_alloc;
    }



   typedef float _v_left_type;
  _v_left_type v_left;

   typedef float _v_right_type;
  _v_right_type v_right;

   typedef float _v_left_stm_type;
  _v_left_stm_type v_left_stm;

   typedef float _v_right_stm_type;
  _v_right_stm_type v_right_stm;





  typedef boost::shared_ptr< ::utils::cmd_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::cmd_vel_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_vel_

typedef ::utils::cmd_vel_<std::allocator<void> > cmd_vel;

typedef boost::shared_ptr< ::utils::cmd_vel > cmd_velPtr;
typedef boost::shared_ptr< ::utils::cmd_vel const> cmd_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::cmd_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::cmd_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::cmd_vel_<ContainerAllocator1> & lhs, const ::utils::cmd_vel_<ContainerAllocator2> & rhs)
{
  return lhs.v_left == rhs.v_left &&
    lhs.v_right == rhs.v_right &&
    lhs.v_left_stm == rhs.v_left_stm &&
    lhs.v_right_stm == rhs.v_right_stm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::cmd_vel_<ContainerAllocator1> & lhs, const ::utils::cmd_vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::cmd_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::cmd_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::cmd_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::cmd_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::cmd_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::cmd_vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "303b665cd559d8efcb8493212084ac67";
  }

  static const char* value(const ::utils::cmd_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x303b665cd559d8efULL;
  static const uint64_t static_value2 = 0xcb8493212084ac67ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/cmd_vel";
  }

  static const char* value(const ::utils::cmd_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 v_left\n"
"float32 v_right\n"
"float32 v_left_stm\n"
"float32 v_right_stm\n"
;
  }

  static const char* value(const ::utils::cmd_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::cmd_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_left);
      stream.next(m.v_right);
      stream.next(m.v_left_stm);
      stream.next(m.v_right_stm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::cmd_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::cmd_vel_<ContainerAllocator>& v)
  {
    s << indent << "v_left: ";
    Printer<float>::stream(s, indent + "  ", v.v_left);
    s << indent << "v_right: ";
    Printer<float>::stream(s, indent + "  ", v.v_right);
    s << indent << "v_left_stm: ";
    Printer<float>::stream(s, indent + "  ", v.v_left_stm);
    s << indent << "v_right_stm: ";
    Printer<float>::stream(s, indent + "  ", v.v_right_stm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_CMD_VEL_H
