// Generated by gencpp from file utils/waypoints.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_WAYPOINTS_H
#define UTILS_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct waypoints_
{
  typedef waypoints_<ContainerAllocator> Type;

  waypoints_()
    : direction_x(0.0)
    , direction_y(0.0)  {
    }
  waypoints_(const ContainerAllocator& _alloc)
    : direction_x(0.0)
    , direction_y(0.0)  {
  (void)_alloc;
    }



   typedef float _direction_x_type;
  _direction_x_type direction_x;

   typedef float _direction_y_type;
  _direction_y_type direction_y;





  typedef boost::shared_ptr< ::utils::waypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::waypoints_<ContainerAllocator> const> ConstPtr;

}; // struct waypoints_

typedef ::utils::waypoints_<std::allocator<void> > waypoints;

typedef boost::shared_ptr< ::utils::waypoints > waypointsPtr;
typedef boost::shared_ptr< ::utils::waypoints const> waypointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::waypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::waypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::waypoints_<ContainerAllocator1> & lhs, const ::utils::waypoints_<ContainerAllocator2> & rhs)
{
  return lhs.direction_x == rhs.direction_x &&
    lhs.direction_y == rhs.direction_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::waypoints_<ContainerAllocator1> & lhs, const ::utils::waypoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::waypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::waypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::waypoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f00f7d19d2890479eddb53378d35106c";
  }

  static const char* value(const ::utils::waypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf00f7d19d2890479ULL;
  static const uint64_t static_value2 = 0xeddb53378d35106cULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/waypoints";
  }

  static const char* value(const ::utils::waypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 direction_x\n"
"float32 direction_y\n"
;
  }

  static const char* value(const ::utils::waypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::waypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction_x);
      stream.next(m.direction_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::waypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::waypoints_<ContainerAllocator>& v)
  {
    s << indent << "direction_x: ";
    Printer<float>::stream(s, indent + "  ", v.direction_x);
    s << indent << "direction_y: ";
    Printer<float>::stream(s, indent + "  ", v.direction_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_WAYPOINTS_H
